---
  # Проверить работоспособность приложения, убедившись, что http://localhost возвращает код 200 
  # и в title страницы строка "React App" (модуль uri).
  - name: Check that a page returns a status 200 and fail if the word 'React App' is not in the page titles
    uri:
      url: http://localhost
      return_content: yes
    register: this
    failed_when: "'React App' not in this.content"

    tags: check_page
