---
  # Создать группу www и пользователя www, добавить пользователя в группу (модуль group, user).  
  - block:
      - group:
          name: www
          state: present
      - user:
          name: www
          group: www

    tags: check_group-user_www
  
  # - name: Ensure group www exists  
  # - name: Add the user www with a primary group of www
    
