---
# Установить unzip для последующей разархивации дистрибутива (модуль apt).      
  - name: Install the latest version of unzip
    apt:
      name: 
        - unzip
      state: latest

  # Удаляю стандартный файл index.nginx-debian.html в var/www/html, если он существует
  - name: Remove file (delete file)
    file:
      path: /var/www/html/index.nginx-debian.html
      state: absent

  # Распаковать дистрибутив в директорию /var/www/html (модуль unarchive).
  - name: Extract {{ distrib_name }}.zip into /var/www
    unarchive:
      src: /tmp/{{ distrib_name }}.zip
      dest: /var/www
      remote_src: yes
